server:
  port: 2525
  servlet:
    context-path: /eshop

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/e-shop
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLInnoDBDialect